#! /bin/sh -e

set_dpms_settings() {
    standby_time=$(gsettings get org.pantheon.dpms standby-time | cut -d" " -f2)

    standby_time=$(($standby_time * 60))

    suspend_time=$(gsettings get org.pantheon.dpms suspend-time | cut -d" " -f2)

    suspend_time=$(($suspend_time * 60))

    off_time=$(gsettings get org.pantheon.dpms off-time | cut -d" " -f2)

    off_time=$(($off_time * 60))

    exec xset dpms $standby_time $suspend_time $off_time
}

gsd_status=$(gsettings get org.gnome.settings-daemon.plugins.power manage-dpms-defaults)

if [ "$gsd_status" = "false" ] ; then
    echo "manage-dpms-defaults is set to false, so we're managing the dpms settings ourselves"
    set_dpms_settings
else
    echo "manage-dpms-defaults is set to true or nonexistent, doing nothing"
fi
