#!/bin/bash
 
    while getopts "12345:6:" OPTION; do
        case ${OPTION} in
            1)
                LANGUAGE=C
                export LANGUAGE
                ufw status;;
            2)
                ufw --force enable;;
            3)
                ufw disable;;
            4)
                LANGUAGE=C
                export LANGUAGE
                ufw status numbered;;
            5)
                ufw $2;;
            6)
                ufw --force delete $OPTARG;;
            \?)
                exit 1;;
        esac
    done